upstream frontend {
    server frontend:3000; # React app container
}

upstream backend {
    server backend:8080; # Backend API container
}

server {

    listen 80; 

    # Check if there is a file or folder that matches the request URI, otherwise show a default 404 error page.
    location / {
        # try_files $uri $uri/ =404;
        proxy_pass http://frontend;
    }

    # Proxy /blogapi requests to the back-apijava1 container
    location /api/employees/ {
        proxy_pass http://backend/api/employees/; # Reference the upstream block
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    
}