upstream react_app {
    server frontend:3000; # React app container
}

upstream spring_app {
    server backend:8080; # Backend API container
}

server {

    # Listen for IPv4 incoming requests on (default) port 80 
    listen 80;  # default_server;
    # Listen for IPv6 incoming requests on (default) port 80 
    # listen [::]:80 default_server;
    
    # Set the root folder for the site and the index files that are acceptable
    # root /usr/share1/nginx/wwwroot;
    # index index.html index.htm;
    
    # Match any host/server name using the (_) which is a catch-all placeholder
    # server_name _;

    # Check if there is a file or folder that matches the request URI, otherwise show a default 404 error page.
    location / {
        # try_files $uri $uri/ =404;
        proxy_pass http://react_app;
    }

    # Proxy /blogapi requests to the back-apijava1 container
    location /api/employees/ {
        proxy_pass http://spring_app/api/employees/; # Reference the upstream block
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}